name: Build, Upload and Deploy Spark Web

on:
  push:
    branches: [ disabled ]

jobs:
  build_frontend:
    name: Build frontend and upload as artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install NPM dependencies and build application
      run: |
          cd frontend
          npm ci
          npm run build
    - name: Upload the frontend build as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: spark-frontend
        path: frontend/dist/

  build_backend:
    name: Build backend
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - uses: actions/checkout@v2
      - name: Download frontend artifact
        uses: actions/download-artifact@v1
        with:
          name: spark-frontend
      - name: Copy frontend files to backend resources
        run: |
          mkdir backend/src/main/resources/templates
          cp -RT spark-frontend backend/src/main/resources/static/
          cp -RT backend/src/main/resources/static/index.html backend/src/main/resources/templates/index.html
      - name: Setup JDK 11
        uses: actions/setup-java@v1.4.0
        with:
          java-version: '11'
      - name: Run Gradle Build
        run: |
          cd backend
          ./gradlew -Dorg.gradle.java.home=/opt/hostedtoolcache/jdk/11.0.8/x64 build
      - name: Copy and Rename generated jar
        run: gradle bundle
      - name: Upload the backend build as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: spark.jar

  deploy_eb:
    name: Deploy application to EB
    needs: build_backend
    runs-on: ubuntu-latest
    steps:
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
      - name: Use timestamp to create application version
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
      - name: Download backend artifact
        uses: actions/download-artifact@v1
        with:
          name: backend
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: spark-web
          environment_name: spark-web
          version_label: "spark-${{ steps.format-time.outputs.replaced }}"
          region: sa-east-1
          deployment_package: backend/spark.jar
      - name: Deployed!
        run: echo App deployed to ELB