#FROM gradle:6.5.1-jdk11 as cache
#RUN mkdir -p /home/gradle/cache_home
#ENV GRADLE_USER_HOME /home/gradle/cache_home
#COPY build.gradle /home/gradle/src/
#WORKDIR /home/gradle/src
#RUN gradle clean build --info --staktrace

FROM gradle:6.5.1-jdk11 as builder
#COPY --from=cache /home/gradle/cache_home /home/gradle/.gradle
COPY . /usr/src/
WORKDIR /usr/src/
RUN gradle build --info --stacktrace

FROM openjdk:11-jre-slim
EXPOSE 80
USER root
WORKDIR /usr/src/
COPY --from=builder /usr/src/build/libs/*.jar ./spark.jar
ENTRYPOINT ["java", "-jar", "spark.jar"]